### ISSUE TITLE
problème avec clime qlima

### ISSUE THREAD

**Issue by OddHD** [ddelec24/mideawifi#1]
le scan détecte bien ma clime mais j'ai le message "Climatiseur 20890720960912 détecté mais à priori non supporté!"
Adresse IP, ID unique et Port sont bien replie automatiquement
et aucun retour d’information et les commandes ne fonctionne pas
jai une clime qlima SC4225 avec une clé wifi EU-OSK103
la version du firmware 3.0.8 (derniere version)
la clime fonction avec l'application midea air sans problème

**Comment by ddelec24** [comment]
Bonjour Odd, je pensais que c'était vous "All" sur le community, 
https://community.jeedom.com/t/plugin-confort-midea/43713/24
vous avez ce post en cours. la clé wifi OSK103, surtout avec les derniers firmware, à l'air d'être plus verrouillée.

je suis l'avancé des tests de mac-zhou (créateur du script python de dialogue) et je me tiendrais prêt à faire une mise à jour de compatibilité si il y a une méthode qui peut être mise en place via jeedom.

**Comment by ddelec24** [comment]
Bonjour,
le plugin a été repris depuis le début en me basant sur le script d'un autre contributeur, l'ancien n'évoluant pas comme je l'espérais. Le plugin prend en charge les équipements cloud/non cloud et d'ici ce week end les déshumidificateurs compatibles.

Je vous invite à supprimer votre équipement si vous l'aviez encore, et mettre le plugin Mideawifi en beta, puis suivre la documentation.
