### ISSUE TITLE
Problème avec un déshumidificateur comfee

### ISSUE THREAD

**Issue by Dartagnan09** [ddelec24/mideawifi#2]
Bonjour,

Pourrait-on voir pour intégrer les déshumidificateurs?

Référence : Comfee' by Midea (MDDF-20DEN7-WF)

**Comment by ddelec24** [comment]
Bonjour, théoriquement, le mode **dry** est compatible de base (il y a juste des options inutiles des AC en plus, ça effectivement c'est une mise à jour possible)

Cependant, le plugin découvre votre déshumidificateur? a t'il fait un message "détecté mais non supporté" lors de la détection?

la compatibilité dépend du contrôleur wifi à l'intérieur de votre appareil, avec vous une référence lisible en quelque part? "OSK-102" par exemple?

merci pour les informations complémentaires, cdt.

**Comment by Dartagnan09** [comment]
Le plugin le découvre, mais les commandes ne semblent pas fonctionner.
J'ai lancer la commande midea-discover sur ma machine jeedom et j'obtiens : 
INFO:msmart.cli:*** Found a unsupported device - type: '0xa1' - version: V3 - ip: 192.168.0.160 - port: 6444 - id: 18691697842045 - sn: 000000P0000000Q1A0681C3029830000 - ssid: net_a1_2983

Dans les spécifications, je trouve les références suivantes : SK102,EU-OSK103,US-OSK103

**Comment by Lim498** [comment]
Bonjour,

Je viens d'acquérir le même déhumidificateur et a exactement le même problème que Dartagnan09.
L'équipement apparaît bien après le scan, mais aucune commande ne passe. Pas de réponse ni rafraichissement de valeurs.
la commande discover me donne exactement le même message au numéro de série et IP près (INFO:msmart.cli:*** Found a unsupported device - type: '0xa1' - version: V3 - ..... ).
Il y a t-il possibilité de faire quelque chose? Je pense que ce n'est pas loin de fonctionner car un déshumidificateur n'est plus ni moins qu'une clim modifiée avec moins de fonctions.

Ci-dessous via l'appli ce qu'on a:

- marche / arrêt
- consigne du taux d'humidité 
- Vitesse de ventilation : faible, moyen, fort
- Mode: déshumidificateur, continu, automatique
- timer par pas de 30min
- Indicateur bac plein

Quelles informations vous faudrait-il pour rendre compatible le plugin? Je suis prêt pour effectuer des tests si nécessaire.

EDIT:
A priori je crois comprendre que l'origine du problème vient du module Wifi qui est utilisé: OSK103.
Effectivement je confirme que je vois bien cette référence dans la doc. (SK102.EU,OSK103,US-OSK103)
Bon bah je croise les doigts pour que vous trouviez un palliatif bientôt.

Bien cordialement

**Comment by ddelec24** [comment]
Effectivement, vous êtes bloqué dans ce cas et les "solutions" sont très complexe à mettre en place.

J'hésite à faire un plugin 2 en 1. Pour les clés OSK103 ça passe par le cloud, donc plus du tout un système en réseau chez vous. Je vais voir suivant mon temps dispo et ce qui existe actuellement.

Par contre je n'ai aucun testeur pour ce type de clim, si vous avez discord et que vous êtes partant, vous pouvez m'ajouter  damien#0602


cdt

**Comment by Lim498** [comment]
Bonjour
Pas de problème pour effectuer des tests
J'ai essayé d'ajouter dans discord damien#602 mais çà ne passe pas, il doit manquer un digit surement
Par contre j'ai créé un serveur dédié pour les tests Midea : https://discord.gg/693ryKcJ
Cordialement

**Comment by ddelec24** [comment]
Première version beta accessible prenant en compte les déshumidificateurs cloud.
**suppression des équipements et relance des dépendances nécessaires.**

Merci à James, si vous détectez d'autres problèmes, nouveau ticket

**Comment by Dartagnan09** [comment]
Je viens d'installer la version Beta et ça a l'air de plutôt très bien fonctionner.
Merci à vous!
